FROM docker.io/oven/bun:1

RUN apt update -y
RUN apt install -y git curl

RUN bun i -g drizzle-kit drizzle-orm pg tsx 

RUN curl -fsSL https://claude.ai/install.sh | bash

ENV PATH="/root/.local/bin:$PATH"